### ISSUE TITLE
Passed, Completed and Terminated statements do not include duration

### ISSUE THREAD

**Issue by thomasturrell** [adlnet/cmi5-Client-Library#10]
I believe that Passed, Completed and Terminated statements must include duration.

**Comment by cawerkenthin** [comment]
+1

**Comment by cawerkenthin** [comment]
Good catch, agreed.

**Comment by cawerkenthin** [comment]
Resolved by commit https://github.com/adlnet/cmi5-Client-Library/commit/964724b1e1ddbcedf1bb4364d9b109474496da16

**Comment by thomasturrell** [comment]
Great, thank you for this.
