### ISSUE TITLE
Multiple Completed and Passed statements could be sent for one registration

### ISSUE THREAD

**Issue by thomasturrell** [adlnet/cmi5-Client-Library#11]
I believe that the cmi5 spec requires that  only one Completed and or Passed statement is sent by the AU.

The AU could use the agent xAPI state resource to store if it has previously sent Completed or Passed statements. I don't believe the AU should attempt to check the existence of the Statements in the LRS because some LMS might prohibit an AU from requesting statements.

**Comment by cawerkenthin** [comment]
This can be resolved by the same local storage mechanism in issue #8

**Comment by thomasturrell** [comment]
It should handle users that logged in using different devices too. However I can see that this might be out of scope.

**Comment by cawerkenthin** [comment]
The AU also has the option to use the State API, which would be a better place than local storage for that situation.


________________________________

**Comment by cawerkenthin** [comment]
Agreed that State API is better place to store data that may need to be shared across devices.
