### ISSUE TITLE
Consider setting withCredentials to true on POST to fetch

### ISSUE THREAD

**Issue by rchadwic** [adlnet/cmi5-Client-Library#4]
This would make it possible for the launching LMS/LRS to restrict access to the fetch endpoint to the client that requested the launch.

**Comment by cawerkenthin** [comment]
Resolved

**Comment by thomasturrell** [comment]
Sorry to comment on an old issue. This is not a requirement of the cmi5 specification and therefore I believe that withCredentials should be set to  false.

It is not possible to use withCredentials in combination with Access-Control-Allow-Origin set to wildcard.

It seems strange to me for an LMS to require credentials to fetch credentials. However I can see an argument for using multiple layers of security.
