### ISSUE TITLE
Double callback of successCallback in getAuthToken

### ISSUE THREAD

**Issue by rchadwic** [adlnet/cmi5-Client-Library#5]
Lacking a "return" on line 285 after auth token is fetched from session storage. The current behavior is read from session, call the successCallback then continue on, make the fetch request, then call either the tokenErrorCallBack incorrectly (since it was read from session anyway) or call successCallback again. Double callback on successCallback leads to fetching the activityState twice.

**Comment by cawerkenthin** [comment]
Resolved.
